#+title: Space Stations
#+date: <2022-10-19 Wed>
#+language: en

There aren't many space stations in <solar system name>, mostly due to the huge costs that each one requires and there isn't much need for space stations.

*The primary habbitat for humans is still ground settlements on planets with breathable atmosphere and sustainable resources.*

** Exoplanets Simulations
+People like to be entertained and so citizen satations have different ways to entertain its citizens. One way is to simulate extreme exoplanets.+
+There is a dedicated area in the arcade section for these kinds of simulations. The sims are quite advanced so they require advanced and expensive technology.+

* Research stations
These aren't really made for comfort and more for scientifical research and effectiveness.

* Emergency Containers
They are small space stations in the form of a cylinder and are only used for emergencies.
It has two entrances/exits, one at the top and one at the bottom with a few floors each doing its thing.

* Parking
/(requires additional thinking)/
Space stations have a dedicated area for parking space ships. Each time a pilot wants to park on a space station they need to ask for docking permission.

If the pilot cannot be identified, they will be asked to stop the engines and wait for a local scan.
If the pilot fails to comply with the regulations, force will be used to deactivate the ship.
