#+title: Space_stations
#+date: <2022-10-19 Wed>
#+language: en
#+updated: <2022-10-19 Wed>

(requires thinking)
Multiple types of space stations:
    1. Citizen stations;
    2. Research stations;
    3. Military/Police stations;


* Citizen stations
These stations have artificial gravity to make the daily citizen life more enjoyable and less of a hassle.

* Emergency Containers
They are small space stations in the form of a cilindar. They are only used for emergencies.
They have a few floors each doing its thing.
It has two entrances/exits, one at the top and one at the bottom.

* Parking
/(requires additional thinking)/
Since space is so vast parking is done by literally parking your ship outisde of a space station. Due to laws space station will always have an active police squad scanning the area so you can rest assured that your ship is in a safe place
Of course to protect the space station from potential hacking attacks, you have to be granted permission to park with your pilot license and the current ship license.
If a ship is to be detected without a license the ship will be deactivated immedietly (using some kind of EMP maybe still gotta think) and checked.
